bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: WrILc64G/mrNovFUy/HTAKClDOO95CWOWhjxaaE2jvvbc46Zkcgaqt53k8mP9Kv60QD07vGKjsVKuCySHfO19PbQyVqFt+Jl1TfeExhsKmtZ1WcETsQaG64zhUhvc45V2aAhEVbYOYknZW7RtYFhfsEB1OxyQHOnSNOynE9fFutfCTT4wNhiOxVlEkOXaISpXx5VVgG4IZF/imIyn9x8M9z6H7XMtoii0byQH7Yi0h2f90uJD4r5BgESppYLv8+kO19Kl1ka5O4GDhp9YDDGRsYurRncn46Igk1ik+bh4pARauByPbbCKLHpDiTKqS8mXCUK+Tw34h+hU0SJ8r29Iq4pXORGLSIvK+SU3fMJEBh0GbvyR0ngGb6uXczvwYmmEhlR2A9cz80jVIJWc46s7HatKiBfjZP3Jb29aWeR7zy5c3iFWAxpElhZETU6JNNQIvw9Br0mP1EecLIhHmiWaVA4yIojRkI2puBaYrTyqd1dIPZyZOIlQlvg8jO2l6shO8xlqb9vQxts2CPbvuLuwz0G6cC+b+Z+vqmfDWoQMQIY1ZeLvHfzXUoV/xPwwMf3ZH0qWZLYGFFn03fORD0Z8YeMClobVltX7RZbRrT4eZUtnYqPGVq3ujo5lf/BCzufg64wqwgyxN0UdVDmcBR2OCWPNfeuqqj7TUpADfLQ4YU=
conda_forge_output_validation: true
